import { parseNum } from '../utils/format';
export const CONSUMO_AGUA_RECOMENDADO_L=3;
export const EQUIPAMENTOS_ENERGIA_PADRAO=[{id:'celular',nome:'Celular',consumoWhDia:12,ativo:true},{id:'luzes',nome:'Luzes',consumoWhDia:8,ativo:true},{id:'gps',nome:'GPS',consumoWhDia:5,ativo:false}];
export function calcBicicleta(v,h,d){v=parseNum(v);h=parseNum(h);d=parseNum(d);const valido=v>0&&h>0;const kmDia=v*h;return{valido,kmDia,distanciaTotal:kmDia*Math.max(d,0),dias:d||0}}
export function montarLinhasAlimentacaoInteligente(config,data={}){return(config||[]).map(a=>{const raw=data[a.id]||{};const unidade=raw.unidade||a.unidades?.[0]?.id;const unidadeCfg=a.unidades?.find(u=>u.id===unidade)||a.unidades?.[0]||{precoPadrao:0,consumoDiarioPadrao:1,label:'un'};const quantidade=parseNum(raw.quantidade);const preco=parseNum(raw.preco!==undefined?raw.preco:unidadeCfg.precoPadrao);const consumo=parseNum(raw.consumo!==undefined?raw.consumo:unidadeCfg.consumoDiarioPadrao);const dias=quantidade>0&&consumo>0?Math.floor(quantidade/consumo):null;return{...a,unidade,quantidade,preco,consumo,valor:quantidade*preco,dias}})}
export function calcAlimentacaoInteligente(linhas=[]){const ativas=linhas.filter(l=>parseNum(l.quantidade)>0);const quantidadeTotal=ativas.reduce((s,l)=>s+parseNum(l.quantidade),0);const valorTotal=ativas.reduce((s,l)=>s+parseNum(l.valor),0);const comDias=ativas.filter(l=>l.dias!==null&&Number.isFinite(l.dias));const gargalo=comDias.length?[...comDias].sort((a,b)=>a.dias-b.dias)[0]:null;const dias=gargalo?gargalo.dias:null;return{valido:ativas.length>0,dias,quantidadeTotal,valorTotal,gargalo}}
export function calcAguaInteligente(litros,reabastece=false,freq=0){litros=parseNum(litros);freq=parseNum(freq);const autonomia=litros/CONSUMO_AGUA_RECOMENDADO_L;return{valido:litros>0,litros,reabastece:!!reabastece,dias:Number(autonomia.toFixed(1)),autonomiaCarregada:Number(autonomia.toFixed(1)),consumoDia:CONSUMO_AGUA_RECOMENDADO_L,suficientePorIntervalo:!!reabastece&&freq>0&&autonomia>=freq,frequenciaDias:freq,baixo:litros>0&&litros<CONSUMO_AGUA_RECOMENDADO_L}}
export function calcEnergia(painel,horasSol,bateria,powerbank,equip=[]){painel=parseNum(painel);horasSol=parseNum(horasSol);bateria=parseNum(bateria);powerbank=parseNum(powerbank);const ativos=(equip||[]).filter(e=>e.ativo!==false);const consumo=ativos.reduce((s,e)=>s+parseNum(e.consumoWhDia),0);const geracaoDiariaWh=painel*horasSol*.75;const reservaWh=bateria+powerbank;const saldo=consumo-geracaoDiariaWh;const autossustentavel=consumo>0&&geracaoDiariaWh>=consumo;const dias=autossustentavel?999:saldo>0?Math.max(0,reservaWh/saldo):0;return{valido:consumo>0,autossustentavel,dias:Number(dias.toFixed(1)),geracaoDiariaWh,consumoDiarioWh:consumo,reservaWh}}
export function calcDinheiro(disponivel,gastoDia){disponivel=parseNum(disponivel);gastoDia=parseNum(gastoDia);return{valido:disponivel>=0&&gastoDia>0,disponivel,gastoDia,dias:gastoDia>0?Number((disponivel/gastoDia).toFixed(1)):0}}
export function montarLinhasPeso(items,data={}){return(items||[]).map(i=>({id:i.id,qtd:data[i.id]?.qtd??String(i.quantity??1),kg:data[i.id]?.kg??''}))}
export function calcPeso(linhas=[]){const total=linhas.reduce((s,l)=>s+parseNum(l.qtd)*parseNum(l.kg),0);const limite=25;return{total,limite,acimaDoLimite:total>limite}}
export function calcCustoViagem(dias,alimentacao,transporte,manutencao,outros){dias=parseNum(dias);alimentacao=parseNum(alimentacao);const total=dias*alimentacao+parseNum(transporte)+parseNum(manutencao)+parseNum(outros);return{total,dias}}
export function calcIndiceGeral(recursos=[]){const candidatos=recursos.filter(r=>!r.neutro&&r.dias!==null&&r.dias!==undefined&&Number.isFinite(Number(r.dias)));if(!candidatos.length)return{dias:null,gargalo:null};const gargalo=[...candidatos].sort((a,b)=>Number(a.dias)-Number(b.dias))[0];return{dias:gargalo.dias,gargalo}}
