export const CHANGELOG=[
 {versao:'1.0.24',data:'23/08/2026',mudancas:[
  'Corrigida a validação do Adaptive Icon no GitHub Actions',
  'Workflow agora valida a mesma cor clara aplicada pelo script de branding Android',
  'Pipeline pode avançar normalmente para a geração do APK após aplicar o novo ícone',
 ]},
 {versao:'1.0.23',data:'23/08/2026',mudancas:[
  'Novo ícone bikepacking integrado ao app, PWA e Android',
  'Arte mais clara com viajante, bicicleta equipada com alforjes e montanha',
  'Launcher normal, redondo e Adaptive Icon atualizados em todas as densidades Android',
  'Composição central preserva bicicleta, viajante e montanha nas máscaras do Android',
 ]},
 {versao:'1.0.22',data:'23/08/2026',mudancas:[
  'Novo ícone oficial Nomade Raiz integrado ao app, PWA e Android',
  'Launcher, round e foreground adaptativo atualizados em todas as densidades Android',
  'Ícone maskable e fundo adaptativo ajustados para evitar bordas claras no launcher',
  'Pipeline de APK reaplica automaticamente a nova identidade após recriar o Android',
 ]},
 {versao:'1.0.21',data:'19/08/2026',mudancas:[
  'GitHub Actions deixa de falhar no setup-node quando o projeto não possui package-lock.json',
  'Cache automático do npm foi desativado explicitamente nos workflows enquanto npm install é usado sem lockfile',
  'Java e cache do Gradle agora são configurados depois que o Capacitor cria a plataforma Android',
  'Diagnóstico do pipeline continua mostrando claramente quando o APK não é produzido',
 ]},
 {versao:'1.0.20',data:'19/08/2026',mudancas:[
  'Nova logo integrada ao Splash e à tela Sobre',
  'Ícones PWA atualizados com favicon, Apple touch icon e variante maskable',
  'Android recebe launcher, round e foreground adaptativo em todas as densidades',
  'GitHub Actions reaplica e valida automaticamente o branding após recriar a plataforma Android',
 ]},
 {versao:'1.0.19',data:'19/08/2026',mudancas:[
  'Build Android APK passa a rodar automaticamente a cada push na main, além de execução manual e tags',
  'Workflow valida o arquivo final, lista as saídas do Gradle e mostra resumo/diagnóstico visível na execução',
  'Actions oficiais atualizadas para checkout v6, setup-node v6, setup-java v5 e upload-artifact v7',
  'Manual da Bike ampliado com diagnóstico, ferramentas, passo a passo, segurança, novas peças e novos problemas de estrada',
  'Busca do Manual passa a pesquisar também sintomas, causas, manutenção, ferramentas, soluções e glossário',
 ]},
 {versao:'1.0.18',data:'19/08/2026',mudancas:[
  'Node atualizado para 24.19 LTS e CI passa a validar explicitamente o toolchain',
  'Capacitor atualizado de 6.2 para 8.5 com Android recriado de forma limpa no GitHub Actions',
  'Android passa a usar o template atual com SDK 36 e Java 21 no pipeline de APK',
  'React atualizado para 19.2.8 e Vite para 8.2.1; TypeScript permanece em 5.9.3 para reduzir risco da migração',
  'Layout passa a consumir as safe areas injetadas pelo SystemBars do Capacitor 8 para evitar conteúdo sob barras do sistema',
 ]},
 {versao:'1.0.17',data:'19/08/2026',mudancas:[
  'PWA passa a gerar Service Worker com cache offline real dos arquivos produzidos pelo Vite',
  'Manifesto ganha ícones de instalação 192/512, máscara e Apple touch icon',
  'Fonte externa removida do carregamento inicial para reduzir dependência de rede',
  'Capacitor existente integrado a um workflow do GitHub Actions que cria a plataforma Android e gera APK',
  'APK debug é publicado como artefato baixável na aba Actions do GitHub',
 ]},
 {versao:'1.0.16',data:'19/08/2026',mudancas:[
  'Planejamento passa a dimensionar alimentação, água e energia pelo número de pessoas',
  'Tipo de viagem agora altera exigência de abrigo e reserva financeira recomendada',
  'Alimentação separa custo informado, custo necessário para o grupo e valor faltante',
  'Reabastecimento de água exige intervalo suficiente e local previsto para status verde',
  'Itens essenciais de segurança são reconhecidos por nome mesmo após serem recriados com outro ID',
  'Autonomia zero passa a ser tratada como insuficiente e novos testes protegem toda a lógica do planejamento',
 ]},
 {versao:'1.0.15',data:'19/08/2026',mudancas:[
  'Desenhos decorativos da Home e de Equipamentos voltaram a ter contraste suficiente após a migração visual',
  'Quantidade zero agora é respeitada nos totais de investimento e de categorias',
  'Alertas de reposição passam a considerar apenas quantidade realmente disponível; itens pendentes contam como estoque zero',
  'Exportação agora separa de verdade Resumo, Compras pendentes e Inventário completo',
  'Testes de regressão adicionados para totais, mínimos e formatos de exportação',
 ]},
 {versao:'1.0.14',data:'14/08/2026',mudancas:[
  'Segunda fase do Design System aplicada a Home, Planejamento, Calculadora, Equipamentos e Manual da Bike',
  'Estilos inline estáticos dessas cinco áreas foram centralizados em CSS; apenas cores realmente dinâmicas permanecem inline',
  'Calculadora deixou de depender do objeto de tema TypeScript e passou a consumir estados visuais via classes e data attributes',
  'Badges, chips, estados de autonomia, seleção de viagem, checklists e ações do Manual ganharam variantes semânticas no Design System',
  'Lint reforçado para impedir regressão visual nas áreas já migradas e exigir o CSS da segunda fase',
 ]},
 {versao:'1.0.13',data:'14/08/2026',mudancas:[
  'Design System próprio criado com tokens CSS para tema, espaçamento, raios, sombras e tipografia',
  'Componentes compartilhados e layouts principais migrados de estilos inline repetidos para classes semânticas',
  'Tema claro/escuro e escala de fonte agora também sincronizam atributos globais usados pelo CSS',
  'Tailwind removido por estar ocioso; PostCSS/Autoprefixer permanecem para o CSS da aplicação',
  'Configurações virou a primeira página completa migrada para o novo sistema visual e acessível',
 ]},
 {versao:'1.0.12',data:'14/08/2026',mudancas:[
  'Suíte automatizada adicionada para Calculadora, Planejamento, reducer e backup/importação',
  'npm run check agora executa lint, TypeScript e testes antes do build do Vite',
  'Testes cobrem regressões de autonomia, limites numéricos, restauração, normalização e compatibilidade de backups',
  'Runner de testes usa TypeScript já presente no projeto, sem adicionar nova biblioteca ou dependência',
 ]},
 {versao:'1.0.11',data:'14/08/2026',mudancas:[
  'Constantes divididas por domínio; constants/index.ts agora funciona apenas como barrel de exportação',
  'Planejamento e Manual da Bike decompostos em componentes menores e responsabilidades mais claras',
  'Refatorações das versões 1.0.9, 1.0.10 e 1.0.11 consolidadas neste pacote',
 ]},
 {versao:'1.0.10',data:'14/08/2026',mudancas:[
  'PlanejamentoPage e ManualBikePage quebrados em componentes e hooks menores',
  'Cálculos derivados e estado de apresentação separados do JSX principal das páginas',
  'Arquivos de página ficaram focados em composição e navegação',
 ]},
 {versao:'1.0.9',data:'14/08/2026',mudancas:[
  'StoreContext simplificado com ações e persistência extraídas para hooks dedicados',
  'Persistência no IndexedDB ganhou debounce por domínio para evitar gravações repetidas durante digitação',
  'Carga inicial e tratamento de falhas de armazenamento ficaram isolados da camada de contexto',
 ]},
 {versao:'1.0.8',data:'14/08/2026',mudancas:[
  'Manual da Bike migrado integralmente para TypeScript/TSX',
  'Todo o código-fonte em src agora usa TypeScript; JavaScript/JSX passa a ser bloqueado pelo lint',
  'Configuração de alimentação ganhou validação tipada na origem, eliminando o TS2352 visto no build do Vercel',
  'Tipos compartilhados do Manual da Bike e contratos de configuração foram reforçados para prevenir regressões',
  'Node.js fixado em 20.x para evitar atualização automática de major no Vercel',
 ]},
 {versao:'1.0.7',data:'14/08/2026',mudancas:[
  'Home, Alertas e Configurações migrados para TypeScript/TSX',
  'Checklists rápidos, nota do dia, edição de mínimos e preferências ganharam contratos de tipos explícitos',
  'Mínimos sugeridos agora preservam o valor 0 definido manualmente e só preenchem itens realmente sem mínimo',
  'Barrels dos três módulos migrados para TypeScript e protegidos contra regressão para JSX/JavaScript',
  'Quantidade de arquivos JSX restante caiu de 10 para 5; apenas o Manual da Bike permanece em JSX',
 ]},
 {versao:'1.0.6',data:'14/08/2026',mudancas:[
  'Planejamento, Diário de Campo e Pontos de Apoio migrados para TypeScript/TSX',
  'Formulários de diário e pontos agora usam contratos tipados compartilhados com o estado persistente',
  'Status do planejamento, tipos de viagem, clima, filtros de pontos e avaliações ganharam tipos explícitos',
  'Importação de backups agora normaliza clima, tipo de ponto e avaliação para valores válidos',
  'Proteções estruturais ampliadas; quantidade de arquivos JSX restante caiu de 16 para 10',
 ]},
 {versao:'1.0.5',data:'14/08/2026',mudancas:[
  'Calculadora e Equipamentos migrados de JSX/JavaScript para TypeScript/TSX',
  'Formulários, propriedades e eventos dessas telas agora possuem contratos de tipos explícitos',
  'Totais de equipamentos e cálculos de alimentação foram centralizados nos services, removendo lógica duplicada da interface',
  'Proteções estruturais ampliadas; quantidade de arquivos JSX restante caiu de 32 para 16',
 ]},
 {versao:'1.0.4',data:'14/08/2026',mudancas:[
  'Extras, Dicas, Exportação e Sobre migrados de JSX para TypeScript/TSX',
  'Modais de dica, apoio e contato agora possuem contratos de propriedades explícitos',
  'Fluxos de backup/importação e QR Code ganharam tipagem sem alterar o comportamento existente',
  'Proteções estruturais ampliadas para impedir o retorno de páginas JSX já migradas',
 ]},
 {versao:'1.0.3',data:'14/08/2026',mudancas:[
  'Base compartilhada da interface migrada de JSX para TypeScript/TSX',
  'App, layouts, hooks e componentes comuns agora possuem contratos de tipos explícitos',
  'Barrels de componentes e layouts migrados para TypeScript com exportação de tipos públicos',
  'Migração preparada para continuar pelas páginas de negócio sem alterar o comportamento atual',
 ]},
 {versao:'1.0.2',data:'11/08/2026',mudancas:[
  'Identidade visual e nome padronizados como Nomade Raiz em todo o app',
  'Página Sobre renovada com versão atual, tecnologias e histórico de mudanças',
  'Ícones em marca-d’água restaurados nos quadros de verificações da tela inicial',
  'README, .gitignore e metadados do GitHub adicionados e padronizados',
  'Checagem automática garante que versão, README e changelogs permaneçam sincronizados',
 ]},
 {versao:'1.0.1',data:'11/08/2026',mudancas:[
  'IndexedDB com Dexie e migração automática',
  'Backup completo e versionado',
  'Versão do app sincronizada com package.json',
  'Componentes visuais básicos e checagens estruturais',
 ]},
 {versao:'1.0.0',data:'11/08/2026',mudancas:[
  'Checklist de equipamentos e verificações rápidas',
  'Planejamento de autonomia',
  'Manual da bicicleta e diário de campo',
  'Funcionamento offline no navegador',
 ]},
];

