import type {
  BikeArea, BikeGlossaryTerm, BikePiece, BikeProblem, BikeQuickTip,
  BikeToolKitItem, ManualBikeTarget,
} from '../types';

export const AREAS_BIKE=[
 {id:'rodas',icone:'🛞',label:'Rodas e pneus'},
 {id:'transmissao',icone:'⛓️',label:'Transmissão'},
 {id:'freios',icone:'🛑',label:'Freios'},
 {id:'estrutura',icone:'🚲',label:'Estrutura e direção'},
] satisfies readonly BikeArea[];

export const PECAS_BIKE=[
 {
  id:'pneu',area:'rodas',icone:'🛞',nome:'Pneu',nivel:'basico',
  funcao:'É o ponto de contato com o solo. A pressão e o estado do pneu influenciam aderência, conforto, consumo de energia e risco de furos.',
  problemasComuns:['Furo','Corte lateral','Baixa pressão','Desgaste irregular'],
  sinaisAtencao:['Trincas ou fios aparecendo','Bolha na lateral','Perda de pressão recorrente','Pneu escapando do aro'],
  ferramentas:['Bomba com manômetro','Espátulas','Remendo ou câmara reserva'],
  antesDeMexer:['Procure o objeto que causou o furo antes de instalar outra câmara.','Confira no flanco do pneu a faixa de pressão recomendada.','Observe se a fita de aro cobre todos os furos dos raios.'],
  manutencao:'Confira pressão antes de viagens longas e inspecione banda de rodagem/laterais. Em cicloviagem, faça uma inspeção visual rápida todos os dias.',
  comoResolver:['Solte o freio se necessário e retire a roda.','Desencaixe apenas um lado do pneu usando espátulas sem ferir a câmara.','Retire a câmara e passe os dedos com cuidado por dentro do pneu procurando espinho, vidro ou rebarba.','Repare ou substitua a câmara, coloque um pouco de ar para dar forma e remonte.','Confira se a câmara não ficou presa entre pneu e aro e calibre progressivamente.'],
  quandoParar:'Não continue rodando se houver bolha grande, corte expondo a carcaça, pneu saindo do aro ou perda rápida de pressão.',
 },
 {
  id:'camara',area:'rodas',icone:'⭕',nome:'Câmara de ar',nivel:'basico',
  funcao:'Mantém o ar pressurizado dentro do pneu nas rodas que não usam sistema tubeless.',
  problemasComuns:['Furo','Válvula rasgada','Remendo soltando','Câmara beliscada'],
  sinaisAtencao:['Perde pressão mesmo sem objeto no pneu','Vazamento próximo à válvula','Dois furos paralelos após impacto'],
  ferramentas:['Bomba','Kit de remendos','Espátulas','Câmara reserva'],
  antesDeMexer:['Marque a posição da válvula para relacionar o furo ao ponto do pneu.','Se houver dois furos lado a lado, aumente a pressão e evite impactos até revisar o conjunto.'],
  manutencao:'Leve ao menos uma câmara compatível e mantenha remendos protegidos de umidade e sujeira.',
  comoResolver:['Infle levemente a câmara e localize o vazamento pelo som, tato ou água quando disponível.','Lixe somente a área necessária se o kit exigir.','Aplique cola/vulcanizante conforme o kit e aguarde o tempo indicado antes do remendo.','Pressione o remendo firmemente e teste antes de remontar.','Se a válvula estiver rasgada, substitua a câmara.'],
  quandoParar:'Uma válvula parcialmente arrancada ou vários furos próximos não são reparos confiáveis para seguir viagem longa.',
 },
 {
  id:'aro-raios',area:'rodas',icone:'🕸️',nome:'Aro e raios',nivel:'intermediario',
  funcao:'Mantêm a roda alinhada e distribuem as cargas entre cubo e pneu.',
  problemasComuns:['Raio quebrado','Roda empenada','Raio frouxo','Aro trincado'],
  sinaisAtencao:['Roda balança lateralmente','Estalos ritmados','Raios com tensões muito diferentes','Freio pega em um ponto da volta'],
  ferramentas:['Chave de raio compatível','Multitool','Abraçadeira plástica para emergência'],
  antesDeMexer:['Gire a roda e descubra se o desvio é do aro ou se o pneu apenas assentou torto.','Marque o ponto de maior desvio antes de tocar nos niples.'],
  manutencao:'Observe tensão dos raios e alinhamento após buracos fortes ou quando a bicicleta estiver muito carregada.',
  comoResolver:['Se apenas um raio quebrou, prenda-o para não atingir o quadro/câmbio.','Alivie o freio se a roda estiver raspando e for indispensável continuar devagar.','Para pequenos desvios, faça ajustes mínimos de 1/4 de volta em raios opostos.','Depois de qualquer correção emergencial, procure centragem adequada em oficina.'],
  quandoParar:'Pare se o aro estiver rachado, vários raios quebrarem ou a roda tocar quadro/garfo mesmo com o freio aberto.',
 },
 {
  id:'cubo',area:'rodas',icone:'⚪',nome:'Cubo e rolamentos',nivel:'intermediario',
  funcao:'Permitem que a roda gire no eixo com baixa resistência e sustentam cargas laterais.',
  problemasComuns:['Folga','Rolamento áspero','Ruído ao girar','Eixo mal fixado'],
  sinaisAtencao:['Roda tem jogo lateral','Raspado ao girar com a roda suspensa','Blocagem/eixo afrouxa repetidamente'],
  ferramentas:['Chaves adequadas ao eixo','Chaves de cone quando aplicável'],
  antesDeMexer:['Confirme primeiro se o eixo está corretamente apertado.','Diferencie folga do cubo de folga no quadro/garfo.'],
  manutencao:'Evite jato de água direto nos rolamentos e faça revisão quando surgir folga ou aspereza.',
  comoResolver:['Aperte corretamente blocagem ou eixo passante.','Teste novamente o jogo lateral.','Em cubos de cone, ajuste somente se souber manter pré-carga correta.','Rolamento selado áspero normalmente exige substituição.'],
  quandoParar:'Não siga com eixo frouxo, rolamento travando ou dano que permita a roda se deslocar lateralmente.',
 },
 {
  id:'corrente',area:'transmissao',icone:'⛓️',nome:'Corrente',nivel:'intermediario',
  funcao:'Transmite a força do pedivela para a roda traseira. Desgaste excessivo acelera o desgaste de cassete e coroas.',
  problemasComuns:['Corrente seca','Elo duro','Elo quebrado','Queda da corrente'],
  sinaisAtencao:['Chiado constante','Ferrugem','Elo que não articula','Corrente pula sob força'],
  ferramentas:['Lubrificante de corrente','Pano','Extrator de corrente','Elo rápido compatível'],
  antesDeMexer:['Descubra o número de velocidades da transmissão para levar elo rápido compatível.','Não use óleo grosso ou graxa externamente: acumulam muita sujeira.'],
  manutencao:'Limpe a sujeira superficial e lubrifique os roletes. Depois, remova o excesso com pano; lubrificante demais também prejudica.',
  comoResolver:['Localize o elo danificado ou duro.','Use o extrator para remover apenas o trecho necessário.','Instale o elo rápido na orientação indicada pelo fabricante quando houver.','Acione o freio e pressione o pedal para travar o elo, se o modelo permitir esse método.','Gire os pedais e teste todas as marchas sem carga antes de voltar a pedalar forte.'],
  quandoParar:'Não aplique força se a corrente estiver prendendo, com placas abertas ou se continuar pulando depois do reparo.',
 },
 {
  id:'cassete',area:'transmissao',icone:'⚙️',nome:'Cassete / catraca',nivel:'intermediario',
  funcao:'Conjunto de pinhões traseiros que fornece as relações de marcha.',
  problemasComuns:['Dentes gastos','Pinhão solto','Corrente pula em marchas específicas','Ruído'],
  sinaisAtencao:['Corrente nova pula apenas em alguns pinhões','Dentes muito pontudos ou em formato de gancho','Folga lateral anormal'],
  ferramentas:['Chave de cassete/catraca específica','Chicote de corrente quando aplicável'],
  antesDeMexer:['Confirme se o problema não vem de cabo, gancheira ou corrente.','Cassete e catraca usam ferramentas e sistemas diferentes.'],
  manutencao:'Mantenha limpo e acompanhe desgaste da corrente para prolongar a vida dos pinhões.',
  comoResolver:['Limpe e observe se o salto ocorre sempre no mesmo pinhão.','Teste ajuste do câmbio antes de condenar o conjunto.','Se houver folga no corpo, verifique aperto apropriado.','Pinhões muito gastos exigem substituição do conjunto ou da peça compatível.'],
  quandoParar:'Se o conjunto estiver solto a ponto de deslocar a corrente ou travar a roda, não continue.',
 },
 {
  id:'cambio',area:'transmissao',icone:'⚙️',nome:'Câmbio traseiro',nivel:'intermediario',
  funcao:'Move a corrente entre os pinhões e mantém tensão adequada na transmissão.',
  problemasComuns:['Marcha pulando','Câmbio desalinhado','Cabo sem tensão','Gancheira torta'],
  sinaisAtencao:['Câmbio muito próximo dos raios','Troca lenta só para um lado','Ruído em todas as marchas','Corrente tenta passar além do maior pinhão'],
  ferramentas:['Chaves Allen','Chave de fenda','Alicate/corta-cabo para manutenção completa'],
  antesDeMexer:['Não ajuste parafusos de limite como primeira tentativa.','Olhe a bike por trás e veja se a gancheira parece alinhada com os pinhões.'],
  manutencao:'Mantenha roldanas limpas, cabos em bom estado e proteja o câmbio de impactos durante transporte.',
  comoResolver:['Teste se o cabo está preso e se a roda está corretamente instalada.','Use o regulador de tensão em incrementos pequenos, geralmente 1/4 de volta.','Suba e desça todas as marchas após cada ajuste.','Se a gancheira estiver claramente torta, limite o uso das marchas críticas e procure alinhamento adequado.'],
  quandoParar:'Pare se o câmbio puder entrar nos raios, a gancheira estiver quebrada ou a corrente travar repetidamente.',
 },
 {
  id:'pedivela',area:'transmissao',icone:'🦿',nome:'Pedivela e coroas',nivel:'intermediario',
  funcao:'Recebem a força dos pedais e a transmitem à corrente pelas coroas.',
  problemasComuns:['Parafuso do braço frouxo','Coroa torta','Dentes gastos','Estalos'],
  sinaisAtencao:['Braço com jogo','Corrente cai sempre no mesmo ponto','Pedal parece balançar junto com o braço'],
  ferramentas:['Chaves Allen ou soquete compatível','Torquímetro para manutenção correta'],
  antesDeMexer:['Descubra se a folga é no pedal, braço do pedivela ou movimento central.','Não continue apertando se a rosca estiver danificada.'],
  manutencao:'Verifique aperto após montagem recente e inspecione dentes/folgas periodicamente.',
  comoResolver:['Segure um braço e tente mover o outro lateralmente.','Aperte fixadores apenas conforme o sistema e torque recomendado.','Gire o conjunto sem corrente, se possível, para separar ruído de transmissão e rolamento.','Substitua peças com rosca ou encaixe danificados.'],
  quandoParar:'Braço do pedivela realmente solto pode destruir o encaixe rapidamente; pare e corrija antes de seguir.',
 },
 {
  id:'vbrake',area:'freios',icone:'🛑',nome:'V-brake',nivel:'basico',
  funcao:'Reduz a velocidade pressionando sapatas contra as laterais do aro.',
  problemasComuns:['Sapata pegando','Freio fraco','Cabo frouxo','Sapata gasta'],
  sinaisAtencao:['Manete encosta no guidão','Sapata toca o pneu','Uma sapata fica presa no aro','Sulcos da sapata desapareceram'],
  ferramentas:['Chaves Allen','Chave de fenda','Pano limpo'],
  antesDeMexer:['Confirme que a roda está bem encaixada.','Não lubrifique aro nem sapatas.'],
  manutencao:'Mantenha a pista de frenagem limpa e troque sapatas antes de atingir o suporte metálico.',
  comoResolver:['Centralize os braços pelos parafusos de mola.','Alinhe as sapatas para tocar somente o aro.','Ajuste tensão do cabo deixando pequena folga para a roda girar livre.','Teste o freio parado com força antes de pedalar.'],
  quandoParar:'Não siga se a sapata tocar o pneu, o cabo estiver desfiando/quebrando ou não houver potência suficiente para parar com segurança.',
 },
 {
  id:'freio-disco',area:'freios',icone:'💿',nome:'Freio a disco',nivel:'intermediario',
  funcao:'Freia por meio de pastilhas que comprimem um rotor preso ao cubo.',
  problemasComuns:['Rotor raspando','Pastilha contaminada','Pouca potência','Rotor empenado'],
  sinaisAtencao:['Chiado forte após óleo/spray','Manete sem resistência','Rotor azul/escurecido por calor','Vazamento em freio hidráulico'],
  ferramentas:['Chaves Allen/Torx compatíveis','Álcool isopropílico para rotor','Espaçador de pastilhas'],
  antesDeMexer:['Nunca acione freio hidráulico com a roda fora sem espaçador.','Evite tocar a pista do rotor com mãos engorduradas.'],
  manutencao:'Mantenha rotor e pastilhas livres de óleo e verifique espessura das pastilhas.',
  comoResolver:['Confirme se a roda está corretamente presa.','Afrouxe levemente a pinça, acione o manete e reaperto de forma uniforme pode recentralizar muitos sistemas.','Limpe o rotor com produto adequado.','Pastilha profundamente contaminada normalmente precisa ser substituída.'],
  quandoParar:'Vazamento hidráulico, rotor trincado ou ausência de potência de frenagem exigem parar e reparar.',
 },
 {
  id:'movimento',area:'estrutura',icone:'🔩',nome:'Movimento central',nivel:'avancado',
  funcao:'Conjunto de eixo/rolamentos que permite a rotação do pedivela no quadro.',
  problemasComuns:['Estalo','Folga','Rolamento áspero','Travamento'],
  sinaisAtencao:['Jogo lateral no pedivela','Sensação granulada ao girar','Estalo sincronizado com cada pedalada'],
  ferramentas:['Ferramenta específica do movimento central','Chaves do pedivela','Torquímetro'],
  antesDeMexer:['Elimine primeiro causas simples: pedal frouxo, coroa, canote e parafusos podem produzir estalos parecidos.'],
  manutencao:'Evite jato direto de água e revise quando surgir folga ou aspereza.',
  comoResolver:['Retire a corrente da coroa e gire o pedivela para sentir os rolamentos.','Cheque folga lateral com as mãos nos braços.','Confirme aperto correto do pedivela.','Movimentos selados com dano interno normalmente são substituídos, não reparados na estrada.'],
  quandoParar:'Se o rolamento estiver travando ou houver folga grande que comprometa o pedivela, não force a viagem.',
 },
 {
  id:'direcao',area:'estrutura',icone:'🧭',nome:'Caixa de direção',nivel:'intermediario',
  funcao:'Permite que garfo e guidão girem suavemente e mantém o conjunto sem folga.',
  problemasComuns:['Folga','Direção dura','Estalo ao frear','Rolamento marcado'],
  sinaisAtencao:['Batida ao acionar freio dianteiro e balançar a bike','Guidão não gira suavemente','Direção tende a parar no centro'],
  ferramentas:['Chaves Allen','Torquímetro recomendado'],
  antesDeMexer:['O parafuso superior do aheadset ajusta pré-carga; os parafusos laterais da mesa travam a posição. A ordem importa.'],
  manutencao:'Cheque folga após impactos e mantenha rolamentos protegidos de água/sujeira.',
  comoResolver:['Acione o freio dianteiro e balance a bicicleta para confirmar folga.','Afrouxe levemente os parafusos laterais da mesa.','Ajuste a tampa superior em pequenos passos até retirar a folga sem endurecer a direção.','Alinhe a mesa com a roda e aperte os parafusos laterais corretamente.'],
  quandoParar:'Direção frouxa, travando ou com componentes rachados é risco de queda; não continue.',
 },
] satisfies readonly BikePiece[];

export const PROBLEMAS_ESTRADA=[
 {
  id:'furo',icone:'🛞',nome:'Pneu furado',gravidade:'baixa',
  causas:['Espinho, arame ou vidro','Baixa pressão e impacto no aro','Câmara beliscada na montagem','Fita de aro danificada'],
  diagnostico:['Veja se o pneu esvaziou de uma vez ou lentamente.','Localize o furo na câmara e compare a posição com pneu/aro.','Procure objeto preso no pneu antes de colocar outra câmara.'],
  ferramentas:['Espátulas','Bomba','Remendo ou câmara reserva'],
  passos:['Leve a bicicleta para um ponto seguro fora da pista.','Retire a roda e abra apenas um lado do pneu.','Remova a câmara e identifique a causa.','Elimine espinho, vidro ou rebarba; confira a fita de aro.','Remende ou troque a câmara, remonte sem beliscar e calibre.'],
  solucaoTemporaria:'Troque a câmara ou aplique remendo confiável. Em corte pequeno de pneu, um reforço interno emergencial pode permitir chegar a um local seguro.',
  solucaoDefinitiva:'Corrija a causa do furo e substitua pneu, fita de aro ou câmara quando houver dano estrutural.',
  naoFaca:['Não instale uma câmara nova sem procurar o objeto causador.','Não rode com pressão muito baixa só para “chegar logo”.'],
  podeContinuar:'Pode continuar se o pneu mantiver pressão e não houver corte/bolha estrutural. Reconfira após alguns quilômetros.',
 },
 {
  id:'corrente-quebrou',icone:'⛓️',nome:'Corrente quebrou',gravidade:'media',
  causas:['Desgaste excessivo','Troca de marcha sob carga forte','Elo danificado ou montagem incorreta'],
  diagnostico:['Encontre o ponto exato da ruptura.','Veja se o câmbio ou a gancheira também sofreram impacto.','Confira se existem outros elos torcidos.'],
  ferramentas:['Multitool com extrator','Elo rápido compatível'],
  passos:['Remova o elo danificado com o extrator.','Passe a corrente corretamente pelas roldanas do câmbio.','Una as pontas com elo rápido compatível com o número de velocidades.','Trave o elo conforme o sistema.','Gire os pedais com a roda suspensa e teste marchas sem carga.'],
  solucaoTemporaria:'Encurte a corrente somente o necessário e feche com elo rápido. Evite combinações extremas de marcha até uma revisão.',
  solucaoDefinitiva:'Meça desgaste e substitua a corrente; revise cassete/coroas se a nova corrente continuar pulando.',
  naoFaca:['Não force um elo incompatível.','Não volte a pedalar forte sem testar o caminho da corrente pelo câmbio.'],
  podeContinuar:'Pode seguir com carga moderada se o reparo estiver articulando livremente e a corrente não pular.',
 },
 {
  id:'marcha-pulando',icone:'⚙️',nome:'Marcha pulando',gravidade:'media',
  causas:['Tensão do cabo incorreta','Gancheira torta','Corrente/cassete gastos','Elo duro'],
  diagnostico:['Descubra se ocorre em um pinhão específico ou em todos.','Teste trocas para marchas maiores e menores separadamente.','Olhe o alinhamento do câmbio por trás.'],
  ferramentas:['Multitool','Chave de fenda','Medidor de corrente se disponível'],
  passos:['Confirme instalação da roda e estado da corrente.','Faça microajuste de tensão do cabo em 1/4 de volta.','Teste novamente todas as marchas.','Se apenas um pinhão pula sob força, suspeite de desgaste.','Se a gancheira estiver torta, evite as marchas que aproximem o câmbio dos raios.'],
  solucaoTemporaria:'Use uma marcha estável e reduza força nas trocas até chegar a um local de reparo.',
  solucaoDefinitiva:'Regular câmbio/gancheira e substituir componentes desgastados conforme diagnóstico.',
  naoFaca:['Não mexa nos parafusos de limite sem saber o que eles restringem.','Não force marcha que empurra o câmbio em direção aos raios.'],
  podeContinuar:'Pode continuar com cautela usando marchas estáveis; pare se o câmbio se aproximar dos raios.',
 },
 {
  id:'freio-pegando',icone:'🛑',nome:'Freio pegando',gravidade:'media',
  causas:['Roda mal encaixada','Freio/pinça descentrado','Aro ou rotor empenado','Sapata/pastilha fora de posição'],
  diagnostico:['Gire a roda e observe se pega o tempo todo ou apenas em um ponto.','Confira primeiro se a roda está corretamente fixada.','Identifique se o contato é sapata/aro ou pastilha/rotor.'],
  ferramentas:['Chave Allen','Chave de fenda conforme sistema'],
  passos:['Reassente a roda no quadro/garfo.','Centralize o freio ou a pinça.','Ajuste folga mínima para a roda girar livre.','Se o aro/rotor estiver empenado, faça apenas correção emergencial pequena ou alivie o freio para chegar à oficina.','Teste frenagem antes de voltar à via.'],
  solucaoTemporaria:'Centralize o conjunto ou alivie minimamente a folga, preservando potência de frenagem.',
  solucaoDefinitiva:'Centrar roda/rotor e regular sapatas/pastilhas corretamente.',
  naoFaca:['Não desative totalmente o único freio funcional.','Não contamine rotor ou pista do aro com óleo.'],
  podeContinuar:'Só continue se a roda girar e ainda houver frenagem segura nos dois comandos disponíveis.',
 },
 {
  id:'freio-fraco',icone:'⚠️',nome:'Freio fraco',gravidade:'alta',
  causas:['Sapata/pastilha gasta ou contaminada','Cabo frouxo','Ar ou vazamento no sistema hidráulico','Aro/rotor molhado ou contaminado'],
  diagnostico:['Teste parado antes de entrar em descida.','Observe se o manete encosta no guidão.','Procure óleo, cabo desfiado, pastilha fina ou vazamento.'],
  ferramentas:['Chaves compatíveis','Pano limpo','Peça de reposição adequada'],
  passos:['Pare em local seguro.','Corrija tensão/posição somente se o sistema permitir ajuste simples.','Limpe pista de frenagem apropriada.','Substitua sapata/pastilha se estiver no limite.','Em hidráulico com vazamento ou manete sem pressão, procure reparo adequado.'],
  solucaoTemporaria:'Somente pequenos ajustes mecânicos seguros. Não existe solução improvisada aceitável para perda séria de freio em descidas.',
  solucaoDefinitiva:'Revisar o sistema, trocar peças desgastadas/contaminadas e sangrar o hidráulico quando necessário.',
  naoFaca:['Não inicie descida longa para “testar”.','Não aplique lubrificante perto das superfícies de frenagem.'],
  podeContinuar:'Se a frenagem não for forte e previsível, não continue em trânsito ou descidas. Segurança vem antes do trajeto.',
 },
 {
  id:'raio-quebrou',icone:'🕸️',nome:'Raio quebrou / roda empenou',gravidade:'media',
  causas:['Impacto forte','Fadiga do raio','Tensão irregular','Carga elevada'],
  diagnostico:['Gire a roda e veja o quanto ela se desloca lateralmente.','Conte raios quebrados e procure trincas no aro.','Confira se o pneu/aro toca quadro, garfo ou freio.'],
  ferramentas:['Chave de raio','Abraçadeira/fita para prender raio solto'],
  passos:['Prenda a ponta do raio quebrado para não atingir outras peças.','Se necessário, alivie o freio para liberar a roda.','Evite mexer em muitos raios sem experiência.','Siga devagar apenas se a roda estiver estruturalmente segura.','Faça centragem e substituição do raio o quanto antes.'],
  solucaoTemporaria:'Prender o raio quebrado e liberar o contato do freio pode permitir deslocamento curto.',
  solucaoDefinitiva:'Substituir o raio e recentrar/tensionar a roda.',
  naoFaca:['Não continue com vários raios quebrados.','Não tente endireitar aro trincado na força.'],
  podeContinuar:'Somente se houver um dano pequeno, roda livre e sem trinca. Reduza velocidade e carga.',
 },
 {
  id:'pedivela-solto',icone:'🦿',nome:'Pedivela ou pedal com folga',gravidade:'alta',
  causas:['Fixação afrouxou','Rosca danificada','Rolamento/movimento central com folga'],
  diagnostico:['Segure o pedal e identifique onde nasce o jogo.','Compare movimento do braço com o eixo.','Procure trincas e rosca danificada.'],
  ferramentas:['Chave Allen/soquete compatível','Chave de pedal conforme sistema'],
  passos:['Pare de aplicar força.','Aperte somente o fixador correto e dentro do sistema de montagem.','Teste o conjunto parado.','Se a folga retornar, não continue apertando repetidamente: pode haver encaixe danificado.'],
  solucaoTemporaria:'Um reaperto correto pode resolver fixação que apenas afrouxou; folga estrutural não deve ser improvisada.',
  solucaoDefinitiva:'Revisar rosca, braço, pedal e movimento central e substituir a peça danificada.',
  naoFaca:['Não pedale forte com braço do pedivela solto.','Não use extensão exagerada na chave sem conhecer o torque.'],
  podeContinuar:'Só se a folga desaparecer completamente após aperto correto. Se voltar, pare.',
 },
 {
  id:'direcao-frouxa',icone:'🧭',nome:'Direção frouxa ou dura',gravidade:'alta',
  causas:['Pré-carga incorreta','Mesa frouxa','Rolamento danificado','Impacto'],
  diagnostico:['Acione o freio dianteiro e balance a bike para sentir batida.','Levante a frente e teste se o guidão gira livre.','Confira alinhamento e aperto da mesa.'],
  ferramentas:['Chaves Allen','Torquímetro recomendado'],
  passos:['Se houver folga em aheadset, afrouxe levemente os parafusos laterais da mesa.','Ajuste a tampa superior em pequenos passos.','Confirme giro livre sem folga.','Alinhe a mesa e aperte os parafusos laterais corretamente.'],
  solucaoTemporaria:'Ajuste simples de pré-carga pode resolver quando não há dano físico.',
  solucaoDefinitiva:'Revisar rolamentos, pistas e fixações; substituir componentes danificados.',
  naoFaca:['Não aperte a tampa superior com a mesa já totalmente travada esperando remover a folga.','Não siga com direção travando.'],
  podeContinuar:'Somente se a direção ficar firme, livre e sem trincas. Caso contrário, pare.',
 },
 {
  id:'parafuso-solto',icone:'🔩',nome:'Parafuso soltando',gravidade:'media',
  causas:['Vibração','Torque inadequado','Rosca danificada','Fixador incompatível'],
  diagnostico:['Descubra qual componente perdeu fixação.','Procure trinca, rosca espanada ou peça deslocada.','Veja se o parafuso é estrutural (mesa, freio, roda, pedivela).'],
  ferramentas:['Multitool','Torquímetro para revisão definitiva'],
  passos:['Reposicione a peça corretamente.','Reaperte de forma progressiva e uniforme.','Teste manualmente se existe folga.','Revise novamente após alguns quilômetros quando for seguro fazê-lo.'],
  solucaoTemporaria:'Reaperte com ferramenta correta sem exceder torque nem mascarar rosca danificada.',
  solucaoDefinitiva:'Revisar rosca, arruelas e fixador; usar trava-rosca apropriado somente quando recomendado para aquele componente.',
  naoFaca:['Não coloque trava-rosca em qualquer parafuso sem critério.','Não force uma rosca que já está espanando.'],
  podeContinuar:'Depende do componente. Fixação de freio, direção, roda ou pedivela precisa estar 100% segura antes de seguir.',
 },
] satisfies readonly BikeProblem[];

export const DICAS_RAPIDAS_BIKE=[
 {id:'abc',icone:'✅',titulo:'Cheque A-B-C antes de sair',resumo:'Ar, brakes (freios) e corrente em menos de dois minutos.',detalhes:['A: aperte os pneus e confira pressão/estado.','B: teste os dois freios parado e verifique se a roda gira livre.','C: observe corrente, trocas de marcha e fixação das rodas.']},
 {id:'foto',icone:'📸',titulo:'Fotografe antes de desmontar',resumo:'Uma foto evita dúvida sobre posição de espaçadores, cabos e caminho da corrente.',detalhes:['Tire uma foto geral e outra aproximada.','Separe parafusos por etapa.','Nunca force uma peça só porque “deveria sair”.']},
 {id:'carga',icone:'🎒',titulo:'Carga muda o comportamento da bike',resumo:'Bagagem aumenta distância de frenagem, esforço de pneus/raios e estabilidade.',detalhes:['Distribua peso baixo e equilibrado.','Reconfira pressão dos pneus com a bike carregada.','Teste frenagem e curvas antes de entrar em tráfego.']},
 {id:'ruido',icone:'👂',titulo:'Ruído novo é aviso, não decoração',resumo:'Estalo, raspado ou clique repetitivo merece diagnóstico antes de virar quebra.',detalhes:['Descubra se o ruído acompanha roda, pedalada ou frenagem.','Teste uma mudança por vez.','Após impacto forte, pare e faça inspeção visual.']},
 {id:'torque',icone:'🔩',titulo:'Apertar mais nem sempre é consertar',resumo:'Excesso de torque pode destruir rosca e componentes leves.',detalhes:['Use a ferramenta do tamanho exato.','Faça apertos progressivos.','Quando houver torque marcado no componente, respeite-o.']},
 {id:'seguranca',icone:'🦺',titulo:'Saiba quando não continuar',resumo:'Freio sem potência, direção frouxa, roda estruturalmente danificada ou pedivela solto justificam parar.',detalhes:['Saia da pista antes de mexer na bicicleta.','Priorize chegar seguro a uma oficina, não “salvar o roteiro”.','Improviso só é aceitável quando mantém controle e estrutura da bike.']},
] satisfies readonly BikeQuickTip[];

export const GLOSSARIO_BIKE=[
 {id:'cassete',termo:'Cassete',definicao:'Conjunto de pinhões encaixado em um freehub na roda traseira.'},
 {id:'catraca',termo:'Catraca / roda-livre',definicao:'Conjunto de pinhões cujo mecanismo de roda livre faz parte da própria peça.'},
 {id:'gancheira',termo:'Gancheira',definicao:'Peça que liga o câmbio traseiro ao quadro e ajuda a proteger o quadro em impactos.'},
 {id:'pedivela',termo:'Pedivela',definicao:'Conjunto de braços onde os pedais são instalados e que movimenta as coroas.'},
 {id:'movimento-central',termo:'Movimento central',definicao:'Eixo/rolamentos que permitem o pedivela girar no quadro.'},
 {id:'talao',termo:'Talão do pneu',definicao:'Borda do pneu que encaixa no aro.'},
 {id:'niple',termo:'Niple do raio',definicao:'Pequena porca que prende e ajusta a tensão do raio no aro.'},
 {id:'rotor',termo:'Rotor',definicao:'Disco metálico do freio a disco preso ao cubo.'},
 {id:'pinca',termo:'Pinça de freio',definicao:'Componente que empurra as pastilhas contra o rotor.'},
 {id:'sapata',termo:'Sapata',definicao:'Elemento de atrito de freios de aro, como V-brake.'},
 {id:'elo-rapido',termo:'Elo rápido',definicao:'Elo removível usado para unir a corrente, que deve ser compatível com a transmissão.'},
 {id:'coroa',termo:'Coroa',definicao:'Engrenagem dianteira ligada ao pedivela.'},
 {id:'blocagem',termo:'Blocagem rápida',definicao:'Mecanismo com alavanca usado para prender algumas rodas ao quadro/garfo.'},
 {id:'eixo-passante',termo:'Eixo passante',definicao:'Eixo rosqueado que atravessa cubo e quadro/garfo, comum em bikes modernas.'},
 {id:'aheadset',termo:'Aheadset',definicao:'Sistema de caixa de direção sem rosca em que a mesa prende diretamente no tubo do garfo.'},
] satisfies readonly BikeGlossaryTerm[];

export const KIT_MINIMO_FERRAMENTAS=[
 {id:'bomba',icone:'💨',nome:'Bomba de ar',motivo:'Recuperar pressão após remendo/troca e corrigir pressão durante a viagem.'},
 {id:'remendo',icone:'🩹',nome:'Kit de remendos',motivo:'Reparar mais de um furo sem gastar todas as câmaras reservas.'},
 {id:'camara-reserva',icone:'⭕',nome:'Câmara reserva',motivo:'Resolve rapidamente furo grande, válvula danificada ou remendo que não pegou.'},
 {id:'multitool',icone:'🔧',nome:'Multitool',motivo:'Apertos e regulagens básicas de freio, câmbio, mesa e acessórios.'},
 {id:'espátula',icone:'🪛',nome:'Espátulas de pneu',motivo:'Retiram o pneu com menos risco de danificar aro/câmara.'},
 {id:'elo',icone:'⛓️',nome:'Elo rápido compatível',motivo:'Recupera uma corrente quebrada sem improvisar união insegura.'},
 {id:'extrator',icone:'🔗',nome:'Extrator de corrente',motivo:'Remove elo danificado antes de instalar o elo rápido.'},
 {id:'abracadeira',icone:'🪢',nome:'Abraçadeiras plásticas',motivo:'Prendem raio quebrado, cabo ou acessório temporariamente sem entrar nas partes móveis.'},
 {id:'pano',icone:'🧻',nome:'Pano pequeno',motivo:'Ajuda a limpar corrente, rotor/aro e mãos durante reparos.'},
] satisfies readonly BikeToolKitItem[];

export const KIT_FERRAMENTA_PARA_ITEM: Readonly<Record<string,string>>={
 bomba:'bomba',remendo:'remendo','camara-reserva':'camara',multitool:'multitool',espátula:'espátula',elo:'elo',extrator:'extrator-corrente',abracadeira:'abracadeira',pano:'pano',
};
export const EQUIPAMENTO_PARA_MANUAL: Readonly<Record<string,ManualBikeTarget>>={
 camara:{tipo:'peca',id:'camara'},remendo:{tipo:'problema',id:'furo'},multitool:{tipo:'peca',id:'corrente'},bomba:{tipo:'peca',id:'pneu'},elo:{tipo:'problema',id:'corrente-quebrou'},
};
