import type {
  BikeArea, BikeAreaId, BikeGlossaryTerm, BikePiece, BikeProblem, BikeSkillLevel,
  BikeToolKitItem, ManualBikeTarget,
} from '../types';

export const AREAS_BIKE=[{id:'rodas',icone:'🛞',label:'Rodas e pneus'},{id:'transmissao',icone:'⛓️',label:'Transmissão'},{id:'freios',icone:'🛑',label:'Freios'},{id:'estrutura',icone:'🚲',label:'Estrutura'}] satisfies readonly BikeArea[];
const peca=(id:string,area:BikeAreaId,icone:string,nome:string,nivel:BikeSkillLevel,funcao:string,problemasComuns:readonly string[],manutencao:string,comoResolver:readonly string[]):BikePiece=>({id,area,icone,nome,nivel,funcao,problemasComuns,manutencao,comoResolver});
export const PECAS_BIKE=[
 peca('pneu','rodas','🛞','Pneu','basico','Faz contato com o solo e absorve parte das irregularidades.',['Furo','Corte','Baixa pressão'],'Inspecione cortes e calibre regularmente.',['Remova a roda se necessário.','Use espátulas para retirar um lado do pneu.','Repare/troque a câmara e remonte sem beliscar.']),
 peca('camara','rodas','⭕','Câmara de ar','basico','Mantém o pneu inflado.',['Furo','Válvula danificada'],'Carregue ao menos uma reserva.',['Localize o furo.','Aplique remendo ou substitua a câmara.','Confira o interior do pneu antes de montar.']),
 peca('corrente','transmissao','⛓️','Corrente','intermediario','Transmite a força dos pedais para a roda.',['Corrente seca','Elo quebrado','Queda da corrente'],'Limpe e lubrifique sem excesso.',['Remova o elo danificado.','Instale um elo rápido compatível.','Teste as marchas com a roda suspensa.']),
 peca('cambio','transmissao','⚙️','Câmbio traseiro','intermediario','Move a corrente entre os pinhões.',['Marcha pulando','Câmbio desalinhado'],'Evite pancadas e confira a gancheira.',['Cheque cabo e gancheira.','Ajuste tensão do cabo em pequenos passos.','Teste todos os pinhões.']),
 peca('vbrake','freios','🛑','V-brake','basico','Reduz a velocidade pressionando sapatas contra o aro.',['Sapata pegando','Freio fraco'],'Mantenha aro e sapatas limpos.',['Centralize os braços.','Alinhe as sapatas no aro.','Ajuste a tensão do cabo.']),
 peca('movimento','estrutura','🔩','Movimento central','avancado','Permite a rotação do pedivela.',['Estalo','Folga','Rolamento áspero'],'Evite lavagem com jato direto.',['Confirme se a folga vem do pedivela.','Aperte conforme o sistema.','Substitua o movimento se houver dano interno.']),
] satisfies readonly BikePiece[];
export const PROBLEMAS_ESTRADA=[
 {id:'furo',icone:'🛞',nome:'Pneu furado',causas:['Espinho ou vidro','Baixa pressão','Câmara beliscada'],ferramentas:['Espátulas','Bomba','Remendo ou câmara'],solucaoTemporaria:'Troque a câmara ou aplique um remendo e calibre com pressão moderada.',solucaoDefinitiva:'Retire o objeto causador, confira a fita de aro e substitua componentes danificados.'},
 {id:'corrente-quebrou',icone:'⛓️',nome:'Corrente quebrou',causas:['Desgaste','Troca de marcha sob carga','Elo danificado'],ferramentas:['Multitool com extrator','Elo rápido'],solucaoTemporaria:'Remova o elo danificado e feche a corrente com elo rápido compatível.',solucaoDefinitiva:'Avalie desgaste da corrente e relação; substitua se necessário.'},
 {id:'freio-pegando',icone:'🛑',nome:'Freio pegando',causas:['Roda desalinhada','Freio descentrado','Sapata fora de posição'],ferramentas:['Chave Allen','Chave de fenda'],solucaoTemporaria:'Centralize o freio ou alivie levemente o cabo para liberar a roda.',solucaoDefinitiva:'Alinhe roda e sapatas e faça regulagem completa.'},
 {id:'parafuso-solto',icone:'🔩',nome:'Parafuso soltando',causas:['Vibração','Torque inadequado'],ferramentas:['Multitool'],solucaoTemporaria:'Reaperte com cuidado, sem exceder o torque.',solucaoDefinitiva:'Revise rosca, arruelas e aplique trava-rosca apropriado quando indicado.'},
] satisfies readonly BikeProblem[];
export const GLOSSARIO_BIKE=[{id:'cassete',termo:'Cassete',definicao:'Conjunto de pinhões na roda traseira.'},{id:'gancheira',termo:'Gancheira',definicao:'Peça que liga o câmbio traseiro ao quadro.'},{id:'pedivela',termo:'Pedivela',definicao:'Conjunto das alavancas onde os pedais são instalados.'},{id:'movimento-central',termo:'Movimento central',definicao:'Rolamentos/eixo que permitem o pedivela girar no quadro.'},{id:'talão',termo:'Talão do pneu',definicao:'Borda do pneu que encaixa no aro.'}] satisfies readonly BikeGlossaryTerm[];
export const KIT_MINIMO_FERRAMENTAS=[{id:'bomba',icone:'💨',nome:'Bomba de ar',motivo:'Recuperar pressão após remendo ou troca de câmara.'},{id:'remendo',icone:'🩹',nome:'Kit de remendos',motivo:'Reparar furos sem gastar a câmara reserva.'},{id:'multitool',icone:'🔧',nome:'Multitool',motivo:'Apertos e regulagens básicas na estrada.'},{id:'espátula',icone:'🪛',nome:'Espátulas de pneu',motivo:'Facilitam a retirada do pneu.'},{id:'elo',icone:'⛓️',nome:'Elo rápido',motivo:'Recuperar uma corrente quebrada.'}] satisfies readonly BikeToolKitItem[];
export const KIT_FERRAMENTA_PARA_ITEM: Readonly<Record<string,string>>={bomba:'bomba',remendo:'remendo',multitool:'multitool',espátula:'espátula',elo:'elo'};
export const EQUIPAMENTO_PARA_MANUAL: Readonly<Record<string,ManualBikeTarget>>={camara:{tipo:'peca',id:'camara'},remendo:{tipo:'problema',id:'furo'},multitool:{tipo:'peca',id:'corrente'},bomba:{tipo:'peca',id:'pneu'}};
