export const DICAS=[
 {id:'agua',icon:'💧',categoria:'Água',titulo:'Nunca dependa de um único ponto de água',texto:'Mantenha sempre uma pequena reserva e reabasteça antes de ficar no limite.\n\nNa prática: marque no planejamento pelo menos uma alternativa de reabastecimento. Em regiões quentes, isoladas ou com muita subida, aumente a margem de segurança. Água disponível no mapa ou indicada por terceiros deve ser confirmada sempre que possível.'},
 {id:'peso',icon:'⚖️',categoria:'Bagagem',titulo:'Menos peso significa mais autonomia',texto:'Revise a bagagem e elimine duplicações. Itens leves que resolvem vários problemas têm prioridade.\n\nNa prática: separe tudo no chão antes de embalar e questione cada item. Peso desnecessário aumenta esforço, consumo de água, desgaste da bicicleta e cansaço acumulado.'},
 {id:'carga',icon:'🎒',categoria:'Bike',titulo:'Distribua a carga na bicicleta',texto:'Mantenha itens pesados baixos e equilibrados entre os lados para preservar dirigibilidade.\n\nNa prática: evite concentrar toda a carga no bagageiro traseiro. Teste a bicicleta carregada antes da viagem e observe se ela continua previsível em curvas, frenagens e subidas.'},
 {id:'chuva',icon:'🌧️',categoria:'Clima',titulo:'Proteja primeiro eletrônicos e roupa seca',texto:'Sacos internos independentes funcionam como segunda barreira contra chuva e condensação.\n\nPrioridade: celular, documentos, power bank, medicamentos e pelo menos uma troca de roupa seca. Mesmo alforjes resistentes à água podem falhar após horas de chuva.'},
 {id:'rota',icon:'🗺️',categoria:'Navegação',titulo:'Tenha rota e referências offline',texto:'Baixe mapas e anote pontos importantes antes de ficar sem sinal.\n\nSalve cidades, mercados, unidades de saúde, oficinas, fontes de água e locais onde seria possível interromper a viagem. Não dependa de um único aplicativo ou de conexão constante.'},
 {id:'energia',icon:'🔋',categoria:'Energia',titulo:'Não espere a bateria chegar ao fim',texto:'Trate energia como um recurso de viagem. Recarregue quando houver oportunidade, mesmo que ainda tenha carga.\n\nCelular, iluminação e navegação podem virar itens de segurança. Mantenha uma reserva de energia para emergências e evite gastar a última carga com tarefas não essenciais.'},
 {id:'comida',icon:'🍱',categoria:'Alimentação',titulo:'Planeje comida por consumo, não só por peso',texto:'Saber que você leva 1 kg de alimento não diz sozinho quantos dias ele vai durar. Compare a quantidade carregada com o consumo diário real.\n\nExemplo: 1 kg de arroz com consumo de 200 g por dia rende cerca de 5 dias para uma pessoa. Ajuste os valores à sua alimentação e ao esforço esperado.'},
 {id:'manutencao',icon:'🔧',categoria:'Manutenção',titulo:'Resolva pequenos sinais antes que virem pane',texto:'Ruídos novos, folgas, marcha pulando e freio diferente do normal merecem atenção.\n\nFaça uma inspeção curta no começo e no fim do dia: pneus, corrente, freios, bagageiros, parafusos e pontos de fixação dos alforjes. Pequenas correções na hora costumam evitar problemas maiores.'},
 {id:'ritmo',icon:'🚲',categoria:'Ritmo',titulo:'Planeje distância com margem para imprevistos',texto:'A média de quilômetros por dia deve considerar subida, vento, chuva, trânsito, paradas e cansaço acumulado.\n\nEvite montar um roteiro em que todos os dias dependem do seu melhor desempenho. Uma margem de tempo deixa a viagem mais segura e reduz decisões ruins por pressa.'},
 {id:'seguranca',icon:'🛡️',categoria:'Segurança',titulo:'Tenha um plano B antes de precisar dele',texto:'Antes de um trecho mais isolado, saiba onde você poderia parar, pedir ajuda ou mudar a rota.\n\nCompartilhe o plano com alguém de confiança quando fizer sentido e mantenha documentos, dinheiro e meios de comunicação acessíveis. Segurança é também reduzir decisões improvisadas sob pressão.'},
] as const;
